name: Compile and Package Kernel v5.10

on:
  pull_request:
    types:
      - closed
    branches:
      - mpdccp_v03_k5.10
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: mpdccp_v03_k5.10

      - name: Compile Linux Kernel # use a debian docker for kernel-compilation
        run: |
          docker run --name kernel_builder -v ${{ github.workspace }}:/mp-dccp debian:11-slim /bin/bash -c '
            cd /mp-dccp
            apt update
            apt install -y cmake gcc build-essential linux-source bc kmod cpio flex libncurses5-dev libelf-dev libssl-dev dwarves bison rsync python3
            cp sampleconfig .config
            scripts/config --disable DEBUG_INFO
            make -sj$(nproc) bindeb-pkg
            mkdir -p pkgs && cp ../*.deb pkgs/
          '

      - name: Upload .deb files to repository
        uses: actions/upload-artifact@v3
        with:
          name: Kernel-deb-files
          path: ${{ github.workspace }}/pkgs

  deploy:
    runs-on: ubuntu-latest
    env: 
      CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
      CI_COMMIT_AUTHOR: Continuous Integration
    needs: build
    steps:
      - name: "Checkout release branch"
        uses: actions/checkout@v3
        with:
          ref: release_5
      - name: "Receive debian files"
        uses: actions/download-artifact@v3
        with:
          name: "Kernel-deb-files"
      - name: "Deploy to Release Branch"
        shell: "bash"
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git add *.deb
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}" && git push || exit 0
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW }}
