name: Compile and Package Kernel v4.14

on:
  push:
    branches:
      - workflow
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: workflow

      - name: Compile Linux Kernel # use a debian docker for kernel-compilation
        run: |
          docker run --name kernel_builder -v ${{ github.workspace }}:/mp-dccp debian:10-slim /bin/bash -c '
            cd /mp-dccp
            #apt update
            #apt install -y cmake gcc build-essential linux-source bc kmod cpio flex libncurses5-dev libelf-dev libssl-dev dwarves bison rsync
            #cp sampleconfig .config
            #make -j$(nproc) bindeb-pkg
            date > ../linux-headers-4.14.111-mpdccp-2022-01-27_4.14.111-mpdccp-2022-01-27-1_amd64.deb
            mkdir -p pkgs && cp ../*.deb pkgs/
          '

      - name: Upload .deb files to repository
        uses: actions/upload-artifact@v4
        with:
          name: Kernel-deb-files
          path: ${{ github.workspace }}/pkgs

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          ref: release_4
      - name: Receive debian files
        uses: actions/download-artifact@v4
        with:
          name: "Kernel-deb-files"
      - name: Deploy to Release Branch
        shell: "bash"
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com"
          git add *.deb
          git commit -a -m "Continuous Integration Build Artifacts" && git push || exit 0
